spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/olxUser
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
